language: java

script:
  # other script steps might be done before running the actual analysis
  - mvn test -B
  - mvn sonar:sonar -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=$SONAR_KEY -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.sources=./src -Dsonar.exclusions=**/**.ucls -Dsonar.tests=./test -Dsonar.language=java -Dsonar.java.binaries=. -Dsonar.java.libraries=./TartanAdventure_jar -Dsonar.java.test.binaries=./test -Dsonar.java.test.libraries=./TartanAdventure_jar
